name: Sync And Deploy

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/pipieline.yaml'
  workflow_dispatch:
    branches:
      - main

defaults:
  run:
    working-directory: ./playbook

env:
  TZ: Asia/Shanghai
  REPO: "artifact.onwalk.net"
  IMAGE: base/${{ github.repository }} 
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync aritfacts
        run: echo "to do"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test aritfacts
        run: echo "to do"

  setup-k3s:
    runs-on: ubuntu-latest
    needs:
      - docker-image

    steps:
      - uses: actions/checkout@v3

      - name: update submodule
        run: |
          sudo apt-get update && sudo apt-get install -y git && git submodule update --init --recursive

      - name: Setup K3S Cluster
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/
          cat > hosts/inventory << EOF
          [master]
          ${{ secrets.HOST_DOMAIN }}               ansible_host=${{ secrets.HOST_IP }}

          [all:vars]
          ansible_port=22
          ansible_ssh_user=${{ secrets.HOST_USER }}
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          ingress_ip=${{ secrets.HOST_IP }}
          EOF
          cat hosts/inventory
          ansible-playbook -i hosts/inventory init_k3s_cluster_std -D
  deploy-app:
    runs-on: ubuntu-latest
    needs: [setup-k3s]

    steps:
      - uses: actions/checkout@v3

      - name: update submodule
        run: |
          sudo apt-get update && sudo apt-get install -y git && git submodule update --init --recursive

      - name: Deploy Keycloak
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/
          cat > hosts/inventory << EOF
          [master]
          ${{ secrets.HOST_DOMAIN }}               ansible_host=${{ secrets.HOST_IP }}

          [all:vars]
          ansible_port=22
          ansible_ssh_user=${{ secrets.HOST_USER }}
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          keycloak_ui_password=$OIDC_ADMIN_PASSWORD
          EOF
          ansible-playbook -i hosts/inventory init_keycloak -D

      - name: Deploy OpenLDAP
        shell: bash
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          sudo apt install jq ansible -y

          mkdir -pv ~/.ssh/
          cat > ~/.ssh/id_rsa << EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          sudo chmod 0400 ~/.ssh/id_rsa
          md5sum ~/.ssh/id_rsa

          mkdir -pv hosts/
          cat > hosts/inventory << EOF
          [master]
          ${{ secrets.HOST_DOMAIN }}               ansible_host=${{ secrets.HOST_IP }}

          [all:vars]
          ansible_port=22
          ansible_ssh_user=${{ secrets.HOST_USER }}
          ansible_ssh_private_key_file=~/.ssh/id_rsa
          ansible_host_key_checking=False
          EOF
          ansible-playbook -i hosts/inventory init_openldap -D
